### ISSUE TITLE
Requests mit Arduino an REST-API

### ISSUE THREAD

**Issue by LukasFelzmann** [VRLAB-HSKL/SmartInventoryManagement#13]
- [ ] WLAN-Modul verbauen/verbinden
- [ ] Arduino mit WLAN verbinden
- [ ] HTTP-Request mit Arduino an unsere REST-API

**Comment by chst0042** [comment]
Da wir uns für einen Raspberry Pi als Microcontroller entschieden haben, kann dieses Issue geschlossen werden.
