### ISSUE TITLE
User profile view

### ISSUE THREAD

**Issue by LukasFelzmann** [VRLAB-HSKL/SmartInventoryManagement#36]
... gemäß Mockup erstellen
![grafik](https://user-images.githubusercontent.com/48865302/185879819-ea8fdc36-05f5-4e0a-83df-faac6dcb3e8c.png)

**Comment by LukasFelzmann** [comment]
@chst0042 Bitte reviewen

**Comment by chst0042** [comment]
Wurde reviewed mit kleinen Verbesserungen und ist in develop gemerged
